Neos:
  EventStore:
    DatabaseStorageAdapter:
      persistence:
        name:
          stream: 'es_stream'

        backendOptions:
          driver: 'pdo_mysql'
          host: '192.168.99.100'
          dbname: 'eventstore'
          user: 'eventstore'
          password: 'eventstore'

        mappingTypes:
          'datetime_micro':
            dbType: 'datetime'
            className: 'Neos\EventStore\DatabaseStorageAdapter\Persistence\Doctrine\DataTypes\DateTimeType'
