Ttree:
  EventStore:
    DatabaseStorageAdapter:
      persistence:
        name:
          commit: 'es_commit'
          stream: 'es_stream'
        backendOptions:
          driver: 'pdo_mysql'
          host: '192.168.99.100'
          dbname: 'eventstore'
          user: 'eventstore'
          password: 'eventstore'
